export const userConstants = {

    FETCH_USER: 'FETCH_USER',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    USER_AUTH_SUCCESS : 'USER_AUTH_SUCCESS',
    USER_AUTH_FAILURE : 'USER_AUTH_FAILURE',
    USER_AUTH_REQUEST : 'USER_AUTH_REQUEST',


    USER_LOGOUT_SUCCESS : 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_REQUEST : 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_FAILURE : 'USER_LOGOUT_FAILURE',

    USER_MOVIE_CHECKOUT_SUCCESS : 'USER_MOVIE_CHECKOUT_SUCCESS',
};

export const movieConstants = {
    FETCH_MOVIE_REQUEST: 'FETCH_MOVIE_REQUEST',
    FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
    FETCH_MOVIE_FAILURE: 'FETCH_MOVIE_FAILURE',
};

export const adminConstants = {
    GET_MOVIES_REQUEST: 'ADMIN_GET_MOVIES_REQUEST',
    GET_MOVIES_SUCCESS: 'ADMIN_GET_MOVIES_SUCCESS',
    GET_MOVIES_FAILURE: 'ADMIN_GET_MOVIES_FAILURE',

    GET_MOVIE_HALLS_REQUEST: 'ADMIN_GET_MOVIE_HALLS_REQUEST',
    GET_MOVIE_HALLS_SUCCESS: 'ADMIN_GET_MOVIE_HALLS_SUCCESS',
    GET_MOVIE_HALLS_FAILURE: 'ADMIN_GET_MOVIE_HALLS_FAILURE',

    ADD_MOVIE_HALL_REQUEST: 'ADMIN_ADD_MOVIE_HALL_REQUEST',
    ADD_MOVIE_HALL_SUCCESS: 'ADMIN_ADD_MOVIE_HALL_SUCCESS',
    ADD_MOVIE_HALL_FAILURE: 'ADMIN_ADD_MOVIE_HALL_FAILURE',

    EDIT_MOVIE_HALL_REQUEST: 'ADMIN_EDIT_MOVIE_HALL_REQUEST',
    EDIT_MOVIE_HALL_SUCCESS: 'ADMIN_EDIT_MOVIE_HALL_SUCCESS',
    EDIT_MOVIE_HALL_FAILURE: 'ADMIN_EDIT_MOVIE_HALL_FAILURE',

    ADD_MOVIE_REQUEST: 'ADMIN_ADD_MOVIE_REQUEST',
    ADD_MOVIE_SUCCESS: 'ADMIN_ADD_MOVIE_SUCCESS',
    ADD_MOVIE_FAILURE: 'ADMIN_ADD_MOVIE_FAILURE',

    GET_MOVIE_REQUEST: 'ADMIN_GET_MOVIE_REQUEST',
    GET_MOVIE_SUCCESS: 'ADMIN_GET_MOVIE_SUCCESS',
    GET_MOVIE_FAILURE: 'ADMIN_GET_MOVIE_FAILURE',

    EDIT_MOVIE_REQUEST: 'ADMIN_EDIT_MOVIE_REQUEST',
    EDIT_MOVIE_SUCCESS: 'ADMIN_EDIT_MOVIE_SUCCESS',
    EDIT_MOVIE_FAILURE: 'ADMIN_EDIT_MOVIE_FAILURE',

    GET_NORMAL_USERS_REQUEST: 'ADMIN_GET_NORMAL_USERS_REQUEST',
    GET_NORMAL_USERS_SUCCESS: 'ADMIN_GET_NORMAL_USERS_SUCCESS',
    GET_NORMAL_USERS_FAILURE: 'ADMIN_GET_NORMAL_USERS_FAILURE',

    EDIT_NORMAL_USER_REQUEST: 'ADMIN_EDIT_NORMAL_USER_REQUEST',
    EDIT_NORMAL_USER_SUCCESS: 'ADMIN_EDIT_NORMAL_USER_SUCCESS',
    EDIT_NORMAL_USER_FAILURE: 'ADMIN_EDIT_NORMAL_USER_FAILURE',

    GET_REVENUE_REQUEST: 'ADMIN_REVENUE_REQUEST',
    GET_REVENUE_SUCCESS: 'ADMIN_REVENUE_SUCCESS',
    GET_REVENUE_FAILURE: 'ADMIN_REVENUE_FAILURE',

};

export const hallAdminConstants = {
    GET_MOVIES_REQUEST: 'HALL_ADMIN_GET_MOVIES_REQUEST',
    GET_MOVIES_SUCCESS: 'HALL_ADMIN_ADMIN_GET_MOVIES_SUCCESS',
    GET_MOVIES_FAILURE: 'HALL_ADMIN_ADMIN_GET_MOVIES_FAILURE',

    GET_HALL_DATA_REQUEST: 'HALL_ADMIN_GET_HALL_DATA_REQUEST',
    GET_HALL_DATA_SUCCESS: 'HALL_ADMIN_GET_HALL_DATA_SUCCESS',
    GET_HALL_DATA_FAILURE: 'HALL_ADMIN_GET_HALL_DATA_FAILURE',

    EDIT_MOVIE_HALL_REQUEST: 'HALL_ADMIN_EDIT_MOVIE_HALL_REQUEST',
    EDIT_MOVIE_HALL_SUCCESS: 'HALL_ADMIN_EDIT_MOVIE_HALL_SUCCESS',
    EDIT_MOVIE_HALL_FAILURE: 'HALL_ADMIN_EDIT_MOVIE_HALL_FAILURE',

    GET_REVENUE_REQUEST: 'HALL_ADMIN_GET_REVENUE_REQUEST',
    GET_REVENUE_SUCCESS: 'HALL_ADMIN_GET_REVENUE_SUCCESS',
    GET_REVENUE_FAILURE: 'HALL_ADMIN_GET_REVENUE_FAILURE',

};